language: groovy
jdk:
  - oraclejdk8

before_script:
  - rm -rf target

# To use new Travis container infrastructure with caching
sudo: false
cache:
  directories:
  - $HOME/.sdkman
  - $HOME/.grails

script: ./travis-build.sh

env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: VI543AeqcYzijvWuB+c6mdb615LiM/N78PQJs1va0bPpXu8Xs0oIS7oUC/Un4BKx/g6gDee6jwPBcSJxWg6YBTyjm1TQnxcLrVsbiBab7BVvizKM7jeNwiv6DfEW+n0SJRiQXQuYd/LKC6g98tisGHBNn8ARSenOckHGroAG4lU=
  - secure: nScXgpO/7z1OTF9jNscWIS2ufLdOfshkHvHL//H1n1LdB2Sqfm5r64dMBGYWMcRzV+1F6jiGVZheKaBiDZmrmWS6bkMJrejgGU2SYPqPR8JGZGv/z1NLzJ3Ekt7lju2MGk/Io3o6DtvAr/k+G6PTrysWSQI/+aswZFIFl9B9Rg8=
  - secure: dfnrq1gwF4ihKaRY1r2OqOvuo357JQ/QMWOiSMdG8VHrTB+brraUd98TWj6Q/ZYEV6OWm0r83E27OsXwrhi51VT0IdYYYd5bvG7msInzxxc+qGPzWEpmgeqSGnNqhYCBoVMHBt5/xIn+t9zSoiBAFEZDXNZ9NTHYihaQe2mMHns=
