---
grails:
   profile: web
info:
   app:
      name: '@info.app.name@'
      version: '@info.app.version@'
      grailsVersion: '@info.app.grailsVersion@'

---
hibernate:
   cache:
      queries: false
      region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
      use_query_cache: false
      use_second_level_cache: false

dataSource:
   dbCreate: update
   driverClassName: org.h2.Driver
   jmxExport: false
   logSql: true
   password:
   pooled: true
   url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
   username: sa
