---
grails:
   profile: web
   spring:
      transactionManagement: false
info:
   app:
      name: '@info.app.name@'
      version: '@info.app.version@'
      grailsVersion: '@info.app.grailsVersion@'

---
hibernate:
   cache:
      queries: false
      use_query_cache: false
      use_second_level_cache: false
   format_sql: true
   use_sql_comments: true

dataSource:
   dbCreate: update
   driverClassName: org.h2.Driver
   jmxExport: false
   password:
   pooled: true
   url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
   username: sa
