grails:
   profile: web-plugin
   doc:
      authors: 'Burt Beckwith'
      license: 'Apache License 2.0'
      title:   'Spring Security Core Plugin'
info:
   app:
      name: '@info.app.name@'
      version: '@info.app.version@'
      grailsVersion: '@info.app.grailsVersion@'
